/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addpost`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/bookrecommend`; params?: Router.UnknownInputParams; } | { pathname: `/bookrecommend2`; params?: Router.UnknownInputParams; } | { pathname: `/bookregister`; params?: Router.UnknownInputParams; } | { pathname: `/dailyreport`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/reviewquestion`; params?: Router.UnknownInputParams; } | { pathname: `/reviewsummary`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na1` | `/na1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na2` | `/na2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na3` | `/na3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na4` | `/na4`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/addpost`; params?: Router.UnknownOutputParams; } | { pathname: `/book`; params?: Router.UnknownOutputParams; } | { pathname: `/bookrecommend`; params?: Router.UnknownOutputParams; } | { pathname: `/bookrecommend2`; params?: Router.UnknownOutputParams; } | { pathname: `/bookregister`; params?: Router.UnknownOutputParams; } | { pathname: `/dailyreport`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/main`; params?: Router.UnknownOutputParams; } | { pathname: `/reviewquestion`; params?: Router.UnknownOutputParams; } | { pathname: `/reviewsummary`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/na1` | `/na1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/na2` | `/na2`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/na3` | `/na3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/na4` | `/na4`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/post/[postId]`, params: Router.UnknownOutputParams & { postId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/addpost${`?${string}` | `#${string}` | ''}` | `/book${`?${string}` | `#${string}` | ''}` | `/bookrecommend${`?${string}` | `#${string}` | ''}` | `/bookrecommend2${`?${string}` | `#${string}` | ''}` | `/bookregister${`?${string}` | `#${string}` | ''}` | `/dailyreport${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/main${`?${string}` | `#${string}` | ''}` | `/reviewquestion${`?${string}` | `#${string}` | ''}` | `/reviewsummary${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/na1${`?${string}` | `#${string}` | ''}` | `/na1${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/na2${`?${string}` | `#${string}` | ''}` | `/na2${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/na3${`?${string}` | `#${string}` | ''}` | `/na3${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/na4${`?${string}` | `#${string}` | ''}` | `/na4${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/addpost`; params?: Router.UnknownInputParams; } | { pathname: `/book`; params?: Router.UnknownInputParams; } | { pathname: `/bookrecommend`; params?: Router.UnknownInputParams; } | { pathname: `/bookrecommend2`; params?: Router.UnknownInputParams; } | { pathname: `/bookregister`; params?: Router.UnknownInputParams; } | { pathname: `/dailyreport`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/main`; params?: Router.UnknownInputParams; } | { pathname: `/reviewquestion`; params?: Router.UnknownInputParams; } | { pathname: `/reviewsummary`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na1` | `/na1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na2` | `/na2`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na3` | `/na3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/na4` | `/na4`; params?: Router.UnknownInputParams; } | `/+not-found` | `/post/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/post/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
    }
  }
}
